"""Add column ManualAllocation to datasheet

Revision ID: 6fa15b2e1a98
Revises: 
Create Date: 2026-04-06 16:31:36.878310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fa15b2e1a98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasheet', schema=None) as batch_op:
        batch_op.alter_column('ManualAllocation',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('IDI',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('lci', schema=None) as batch_op:
        batch_op.alter_column('Background_process',
               existing_type=mysql.VARCHAR(length=48),
               nullable=False)
        batch_op.alter_column('Code',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('GWP',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Smog',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Acidification',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Eutrophication',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Carcinogenics',
               existing_type=mysql.DECIMAL(precision=7, scale=6),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Non_carcinogenics',
               existing_type=mysql.DECIMAL(precision=7, scale=6),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Respiratory_effects',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Ecotoxicity',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Fossil_fuel_depletion',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Ozone_depletion',
               existing_type=mysql.DECIMAL(precision=7, scale=6),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('Code'))

    with op.batch_alter_table('mtransp', schema=None) as batch_op:
        batch_op.alter_column('IDM',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False,
               autoincrement=False)
        batch_op.alter_column('EnterBy',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.alter_column('IDS',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('unit_alias', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_index(batch_op.f('idx_unit_alias_canonical_unit'))

    with op.batch_alter_table('unit_conversion', schema=None) as batch_op:
        batch_op.alter_column('factor_to_si',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_index(batch_op.f('idx_unit_conversion_category'))

    with op.batch_alter_table('uom', schema=None) as batch_op:
        batch_op.alter_column('IDU',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False,
               autoincrement=False)
        batch_op.alter_column('Unit',
               existing_type=mysql.CHAR(length=5),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_uname_unit'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('regeneration_mode',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('regeneration_mode',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('uom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_uname_unit'), ['UName', 'Unit'], unique=False)
        batch_op.alter_column('Unit',
               existing_type=sa.String(length=5),
               type_=mysql.CHAR(length=5),
               existing_nullable=False)
        batch_op.alter_column('IDU',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('unit_conversion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_unit_conversion_category'), ['category'], unique=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('factor_to_si',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('unit_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_unit_alias_canonical_unit'), ['canonical_unit'], unique=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.alter_column('IDS',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('mtransp', schema=None) as batch_op:
        batch_op.alter_column('EnterBy',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
        batch_op.alter_column('IDM',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('lci', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Code'), ['Code'], unique=True)
        batch_op.alter_column('Ozone_depletion',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=7, scale=6),
               existing_nullable=True)
        batch_op.alter_column('Fossil_fuel_depletion',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Ecotoxicity',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Respiratory_effects',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Non_carcinogenics',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=7, scale=6),
               existing_nullable=True)
        batch_op.alter_column('Carcinogenics',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=7, scale=6),
               existing_nullable=True)
        batch_op.alter_column('Eutrophication',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Acidification',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Smog',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('GWP',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Code',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('Background_process',
               existing_type=mysql.VARCHAR(length=48),
               nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('IDI',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('datasheet', schema=None) as batch_op:
        batch_op.alter_column('ManualAllocation',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
