"""Add new column into table Element

Revision ID: c4bb2c69741f
Revises: 
Create Date: 2026-01-10 23:22:00.216341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4bb2c69741f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matrix_a_raw')
    with op.batch_alter_table('element', schema=None) as batch_op:
        batch_op.alter_column('Global_Val',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('IDI',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('lci', schema=None) as batch_op:
        batch_op.alter_column('Background_process',
               existing_type=mysql.VARCHAR(length=48),
               nullable=False)
        batch_op.alter_column('Code',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('GWP',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Smog',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Acidification',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Eutrophication',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Carcinogenics',
               existing_type=mysql.DECIMAL(precision=7, scale=6),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Non_carcinogenics',
               existing_type=mysql.DECIMAL(precision=7, scale=6),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Respiratory_effects',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Ecotoxicity',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Fossil_fuel_depletion',
               existing_type=mysql.DECIMAL(precision=10, scale=9),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.alter_column('Ozone_depletion',
               existing_type=mysql.DECIMAL(precision=7, scale=6),
               type_=sa.Numeric(precision=16, scale=10),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('Code'))

    with op.batch_alter_table('mtransp', schema=None) as batch_op:
        batch_op.alter_column('IDM',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False,
               autoincrement=False)
        batch_op.alter_column('EnterBy',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.alter_column('IDS',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('uom', schema=None) as batch_op:
        batch_op.alter_column('IDU',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False,
               autoincrement=False)
        batch_op.alter_column('Unit',
               existing_type=mysql.CHAR(length=5),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_uname_unit'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('regeneration_mode',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('regeneration_mode',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('uom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_uname_unit'), ['UName', 'Unit'], unique=False)
        batch_op.alter_column('Unit',
               existing_type=sa.String(length=5),
               type_=mysql.CHAR(length=5),
               existing_nullable=False)
        batch_op.alter_column('IDU',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.alter_column('IDS',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('mtransp', schema=None) as batch_op:
        batch_op.alter_column('EnterBy',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
        batch_op.alter_column('IDM',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('lci', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Code'), ['Code'], unique=True)
        batch_op.alter_column('Ozone_depletion',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=7, scale=6),
               existing_nullable=True)
        batch_op.alter_column('Fossil_fuel_depletion',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Ecotoxicity',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Respiratory_effects',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Non_carcinogenics',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=7, scale=6),
               existing_nullable=True)
        batch_op.alter_column('Carcinogenics',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=7, scale=6),
               existing_nullable=True)
        batch_op.alter_column('Eutrophication',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Acidification',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Smog',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('GWP',
               existing_type=sa.Numeric(precision=16, scale=10),
               type_=mysql.DECIMAL(precision=10, scale=9),
               existing_nullable=True)
        batch_op.alter_column('Code',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('Background_process',
               existing_type=mysql.VARCHAR(length=48),
               nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('IDI',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False,
               autoincrement=False)

    with op.batch_alter_table('element', schema=None) as batch_op:
        batch_op.alter_column('Global_Val',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))

    op.create_table('matrix_a_raw',
    sa.Column('Flow', mysql.VARCHAR(length=26), nullable=True),
    sa.Column('Flow_ID', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('Process_1', mysql.VARCHAR(length=5), server_default=sa.text("'0'"), nullable=False),
    sa.Column('Unit_1', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('Process_2', mysql.VARCHAR(length=5), server_default=sa.text("'0'"), nullable=False),
    sa.Column('Unit_2', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('Process_3', mysql.VARCHAR(length=5), server_default=sa.text("'0'"), nullable=False),
    sa.Column('Unit_3', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('Process_4', mysql.VARCHAR(length=5), server_default=sa.text("'0'"), nullable=False),
    sa.Column('Unit_4', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('Process_5', mysql.VARCHAR(length=5), server_default=sa.text("'0'"), nullable=False),
    sa.Column('Unit_5', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('Process_6', mysql.VARCHAR(length=5), server_default=sa.text("'0'"), nullable=False),
    sa.Column('Unit_6', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
