"""Remove cascading constraint

Revision ID: e619a58a88d2
Revises: 
Create Date: 2025-11-18 09:56:18.418960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e619a58a88d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element', schema=None) as batch_op:
        batch_op.alter_column('IDI',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_ename_idi'))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('IDI',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False)

    with op.batch_alter_table('lci', schema=None) as batch_op:
        batch_op.alter_column('Code',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
        batch_op.drop_index(batch_op.f('Code'))

    with op.batch_alter_table('matrix_a_raw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Flow_id', sa.String(length=5), nullable=True))
        batch_op.alter_column('Process_1',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('Process_2',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('Process_3',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('Process_4',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('Process_5',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('Process_6',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('Flow_ID')

    with op.batch_alter_table('mtransp', schema=None) as batch_op:
        batch_op.alter_column('IDM',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.alter_column('EnterBy',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('UpdateBy',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.alter_column('IDS',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('Region',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)

    with op.batch_alter_table('uom', schema=None) as batch_op:
        batch_op.alter_column('IDU',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.alter_column('Unit',
               existing_type=mysql.CHAR(length=5),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_uname_unit'))

    with op.batch_alter_table('user_parameter_value', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_parameter'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_task'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['IDT'], ['IDT'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'parameter', ['parameter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_parameter_value', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_task'), 'tasks', ['IDT'], ['IDT'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_parameter'), 'parameter', ['parameter_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('uom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_uname_unit'), ['UName', 'Unit'], unique=False)
        batch_op.alter_column('Unit',
               existing_type=sa.String(length=5),
               type_=mysql.CHAR(length=5),
               existing_nullable=False)
        batch_op.alter_column('IDU',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('Region',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)

    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.alter_column('IDS',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('mtransp', schema=None) as batch_op:
        batch_op.alter_column('UpdateBy',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
        batch_op.alter_column('EnterBy',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
        batch_op.alter_column('IDM',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('matrix_a_raw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Flow_ID', mysql.VARCHAR(length=5), nullable=True))
        batch_op.alter_column('Process_6',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('Process_5',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('Process_4',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('Process_3',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('Process_2',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('Process_1',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('Flow_id')

    with op.batch_alter_table('lci', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Code'), ['Code'], unique=True)
        batch_op.alter_column('Code',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('IDI',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('element', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ename_idi'), ['EName', 'IDI'], unique=False)
        batch_op.alter_column('IDI',
               existing_type=sa.String(length=6),
               type_=mysql.CHAR(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###
